In [220]:
import matplotlib.pyplot as plt
import numpy as np
from io import BytesIO
from PIL import Image
import tensorflow as tf
from keras.utils import to_categorical
import cv2
import os


In [221]:
path = "E:/downloads/3rd sem engineering/WEB  DEVELOPMENT/Major Project/Dataset/New Plant Diseases Dataset(Augmented)/New Plant Diseases Dataset(Augmented)/train"  # Replace with the path to your dataset
className = os.listdir(path)
className.sort() 
className=className[:]
print(className)
imageData = []
labelData = []

for count, folder in enumerate(className):
    folder_path = os.path.join(path, folder)
    images = os.listdir(folder_path)
    print("Loading Folder --", folder, "The Count of Classes ==> ", count)
    for i in range(10):
        image = cv2.imread(os.path.join(folder_path, images[i]))
        image = cv2.resize(image, (70, 70))
        imageData.append(image)
        labelData.append(count)

['Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust', 'Apple___healthy', 'Blueberry___healthy', 'Cherry_(including_sour)___Powdery_mildew', 'Cherry_(including_sour)___healthy', 'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 'Corn_(maize)___Common_rust_', 'Corn_(maize)___Northern_Leaf_Blight', 'Corn_(maize)___healthy', 'Grape___Black_rot', 'Grape___Esca_(Black_Measles)', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 'Grape___healthy', 'Orange___Haunglongbing_(Citrus_greening)', 'Peach___Bacterial_spot', 'Peach___healthy', 'Pepper,_bell___Bacterial_spot', 'Pepper,_bell___healthy', 'Potato___Early_blight', 'Potato___Late_blight', 'Potato___healthy', 'Raspberry___healthy', 'Soybean___healthy', 'Squash___Powdery_mildew', 'Strawberry___Leaf_scorch', 'Strawberry___healthy', 'Tomato___Bacterial_spot', 'Tomato___Early_blight', 'Tomato___Late_blight', 'Tomato___Leaf_Mold', 'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite', 'Tomato___Target_Sp

In [222]:
data = np.array(imageData)
data = data.astype("float32")
data = data/255.0

label = np.array(labelData)
print(data.shape)
label_num = to_categorical(label, len(className))
len(label_num)

(380, 70, 70, 3)


380

In [223]:
MODEL = tf.keras.models.load_model(r"E:\downloads\3rd sem engineering\WEB  DEVELOPMENT\Major Project\FarmersWebsite\farmerswebsite\api\my_model5.h5")
MODEL.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 sequential_2 (Sequential)   (None, 70, 70, 3)         0         
                                                                 
 conv2d_5 (Conv2D)           (None, 70, 70, 16)        1216      
                                                                 
 max_pooling2d_5 (MaxPoolin  (None, 35, 35, 16)        0         
 g2D)                                                            
                                                                 
 conv2d_6 (Conv2D)           (None, 35, 35, 32)        8224      
                                                                 
 max_pooling2d_6 (MaxPoolin  (None, 17, 17, 32)        0         
 g2D)                                                            
                                                                 
 conv2d_7 (Conv2D)           (None, 17, 17, 64)       

In [224]:
CLASS_NAMES=['Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust', 'Apple___healthy', 
             'Blueberry___healthy', 'Cherry_(including_sour)___Powdery_mildew', 'Cherry_(including_sour)___healthy',
             'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 'Corn_(maize)___Common_rust_', 
             'Corn_(maize)___Northern_Leaf_Blight', 'Corn_(maize)___healthy', 'Grape___Black_rot', 
             'Grape___Esca_(Black_Measles)', 'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 'Grape___healthy',
             'Orange___Haunglongbing_(Citrus_greening)', 'Peach___Bacterial_spot', 'Peach___healthy', 
             'Pepper,_bell___Bacterial_spot', 'Pepper,_bell___healthy', 'Potato___Early_blight', 
             'Potato___Late_blight', 'Potato___healthy', 'Raspberry___healthy', 'Soybean___healthy', 
             'Squash___Powdery_mildew', 'Strawberry___Leaf_scorch', 'Strawberry___healthy', 
             'Tomato___Bacterial_spot', 'Tomato___Early_blight', 'Tomato___Late_blight', 'Tomato___Leaf_Mold', 
             'Tomato___Septoria_leaf_spot', 'Tomato___Spider_mites Two-spotted_spider_mite', 
             'Tomato___Target_Spot', 'Tomato___Tomato_Yellow_Leaf_Curl_Virus', 'Tomato___Tomato_mosaic_virus', 
             'Tomato___healthy']

In [225]:
test_loss, test_accuracy = MODEL.evaluate(data, label_num)

12/12 [==============================] - 1s 32ms/step - loss: 0.4079 - accuracy: 0.8789


In [230]:
img_path =(r"E:\downloads\3rd sem engineering\WEB  DEVELOPMENT\Major Project\FarmersWebsite\farmerswebsite\public\testdata\PotatoHealthy1.JPG")
img = plt.imread(img_path)
img = cv2.resize(img, (70, 70)) 
# Resize the image to match the model's expected sizing
img=np.array(img)
img = img.astype("float32")
img = img / 255.0
img= np.reshape(img, (1, 70, 70, 3))
pred = MODEL.predict(img)[0]
predicted_class = CLASS_NAMES[np.argmax(pred)]
print(predicted_class)


[[[179 166 175]
  [173 160 169]
  [178 165 174]
  ...
  [172 159 169]
  [165 152 162]
  [173 160 170]]

 [[176 163 172]
  [175 162 171]
  [167 154 163]
  ...
  [170 157 167]
  [170 157 167]
  [169 155 166]]

 [[178 165 174]
  [173 160 169]
  [173 160 170]
  ...
  [172 159 169]
  [170 157 167]
  [168 155 165]]

 ...

 [[190 171 177]
  [193 174 180]
  [170 151 157]
  ...
  [152 141 149]
  [190 179 187]
  [177 166 174]]

 [[148 129 135]
  [159 140 146]
  [153 134 140]
  ...
  [163 152 160]
  [212 201 209]
  [198 187 195]]

 [[170 151 157]
  [143 124 130]
  [162 143 149]
  ...
  [165 154 162]
  [176 164 173]
  [175 164 172]]]
1/1 [==============================] - 0s 23ms/step
Pepper,_bell___healthy


In [228]:
# for img in range(380):
#     i = np.reshape(data[img], (1, 70, 70, 3))
#     prediction = MODEL.predict(i)
#     predicted_class = CLASS_NAMES[np.argmax(prediction)]
#     true_class = CLASS_NAMES[np.argmax(label_num[img])]
#     print("\n",predicted_class)
#     print("\nactual clss :",true_class)
    # pred = MODEL.predict(img)[0]

    # # Get the predicted class
    # predicted_class = CLASS_NAMES[np.argmax(pred)]
    # print(predicted_class)
    # print(CLASS_NAMES[np.argmax(label_num)[0]])
